### ISSUE TITLE
Feature: Set maximum height and scroll vertically

### ISSUE THREAD

**Issue by xsorifc28** [0m4r/MMM-SoccerLiveScore#12]
Feature request:
It would be nice to limit the height to a certain amount and vertically scroll the hidden parts of the information.

**Comment by 0m4r** [comment]
This is something I will not implement, you can customize that on your own (see the answer to your other question.
Or you can use customize your Magic Mirror CSS: https://docs.magicmirror.builders/modules/customcss.html

**Comment by xsorifc28** [comment]
Duplicate of #8
