### ISSUE TITLE
MMM-SoccerLiveScore is not loading at all

### ISSUE THREAD

**Issue by benzoto** [0m4r/MMM-SoccerLiveScore#6]
Hi :) 

First I would like to thank you for all your efforts to make our lives better :) 

I would like to raise an issue that I'm trying to fix for the last couple of weeks.

I have setup MM and the module as per the instructions however it is not loading at all and I can see the following errors in the console.

There seem to be some sort of issue with the LeaguesIDs but I did followed the instructions :) my Module config is as follows:

CONFIG!

{
                module: 'MMM-SoccerLiveScore',
                position: 'top_right',
                header: 'Live-Scores',
                        config: {
                                leagues:  [1, 35, 17, 8, 23],
                                        showNames: true,
                                        showLogos: true,
                                        displayTime: 600 * 1000,
                                        showStandings: true,
                                        showTables: true,
                                        showScorers: true,
                                }
                },

ERRORS!

0|MagicMir | [29.11.2021 14:08.36.739] [ERROR] undefined getLeagueIds Error: connect ECONNREFUSED 82.223.33.66:443
0|MagicMir |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
0|MagicMir |   errno: 'ECONNREFUSED',
0|MagicMir |   code: 'ECONNREFUSED',
0|MagicMir |   syscall: 'connect',
0|MagicMir |   address: '82.223.33.66',
0|MagicMir |   port: 443
0|MagicMir | }

**Comment by 0m4r** [comment]
Hi, this is the same issue already reported on the MM forum: https://forum.magicmirror.builders/topic/1169/mmm-soccerlivescore/119?_=1638190477370

Would it be possible for you to try updating the code base once again?
I have made a fix last Friday and it should at least now load up the data (but there is some issue with the live updates of the results I am looking into it!)

to update the module, please do go into the folder you have cloned the module and simply do a "git pull -r".
Once this is done, do restart magic mirror :)

**Comment by benzoto** [comment]
It did worked!! Thx a lot. Quick question, when you say live updates of the results, I can only see previous results and no future ones, how do I enable this feature too?

**Comment by 0m4r** [comment]
If I could see future results, I will not want to share them with everyone! :P 

You see the "past results for a while, the "new" ones usually come up a day or sometimes before they are started.
If this is not the case, please open another bug! Thanks!

**Comment by benzoto** [comment]
Hahaha :) Thx What I actually meant is Future Fixtures :) hahaha. About the results, I totally agree with you, you should not share them :D :D 

How can I see what is up next with the leagues, this is what I wanted to ask

**Comment by 0m4r** [comment]
the "next" games schedule and results should pop-i automagically as they did before when the API returns them.
at the bottom of the standings (where the results are) there should be a little line that says when you can expect the data to update: "Next API request DATE_HERE" (but, on some occasions, the date may be wrong - here is where I am working to fix it)

**Comment by benzoto** [comment]
Understood. THX again for all your work!!
