### ISSUE TITLE
Tables are overflowing on top of other modules

### ISSUE THREAD

**Issue by xsorifc28** [0m4r/MMM-SoccerLiveScore#8]
This should be a simple css fix, to set the maximum height of the module so that it does not overlap on top of other modules.

**Comment by 0m4r** [comment]
would you be able to attach a screenshot? 
I am not sure I can replicate it.

**Comment by xsorifc28** [comment]
I'm not able to set a max height on the display. I'd like to truncate it to 100px and have it scroll if there is an overflow.

**Comment by 0m4r** [comment]
a bit of a late reply, but this worked for me:

<img width="780" alt="image" src="https://github.com/0m4r/MMM-SoccerLiveScore/assets/451638/f7fe02fa-1811-42aa-9a73-ddf6f1f8493a">

**Comment by xsorifc28** [comment]
I don't see how that css will make it autoscroll?
Wouldn't that only work with mouse scrolling?

**Comment by 0m4r** [comment]
The scroll feature is implemented in javascript. Your question is about how to limit the component height, that css does it.

**Comment by xsorifc28** [comment]
I see. Thanks for your negligence on the feature request.

**Comment by msnek** [comment]
I am having the same issue. Where should that css part go?

**Comment by 0m4r** [comment]
you can add it to the custom.css file: https://docs.magicmirror.builders/modules/customcss.html
